feat: add spec retries

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -100,7 +100,27 @@ runs:
         # Step-specific
         SCREENSHOT_ROOT: ${{ env.AUTH_REACT__SCREENSHOT_DIR }}
       shell: bash
-      run: npx mocha --spec ${{ inputs.spec }}
+      run: |
+        retry() {
+          local retries="$1" # First argument
+          local command="$2" # Second argument
+
+          # Run the command, and save the exit code
+          $command
+          local exit_code=$?
+
+          # If the exit code is non-zero (i.e. command failed), and we have not
+          # reached the maximum number of retries, run the command again
+          if [[ $exit_code -ne 0 && $retries -gt 0 ]]; then
+            echo -e "Tests failed [$retries retries remaining]\n\n\n"
+            retry $(($retries - 1)) "$command"
+          else
+            # Return the exit code from the command
+            return $exit_code
+          fi
+        }
+
+        retry 3 "npx mocha --spec ${{ inputs.spec }}"
 
     - if: always()
       name: Fix paths
