fix: move check for nextjs to bash code

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -81,7 +81,7 @@ runs:
       shell: bash
       run: npx react-scripts start &> $AUTH_REACT__LOG_DIR/frontend.log &
 
-    - if: ${{ env.HAS_NEXTJS_EXAMPLES == 'true' || env.HAS_NEXTJS_EXAMPLES == true }} && ${{ env.TESTING_PLATFORM == 'nextjs' }}
+    - if: ${{ env.TESTING_PLATFORM == 'nextjs' }}
       name: Start auth-react nextjs server
       working-directory: ${{ inputs.path }}/examples/for-tests-nextjs/
       env:
@@ -91,7 +91,15 @@ runs:
         CI: true
         PORT: ${{ env.AUTH_REACT__PORT }}
       shell: bash
-      run: npm run dev &> $AUTH_REACT__LOG_DIR/frontend.log &
+      run: |
+        if [ "$TESTING_PLATFORM" == "nextjs" ]; then
+          if [ "$HAS_NEXTJS_EXAMPLES" == "true" ]; then
+            npm run dev &> $AUTH_REACT__LOG_DIR/frontend.log &
+          else
+            echo "nextjs test found but examples not found."
+            exit 1
+          fi
+        fi
 
     - name: Wait for servers
       env:
diff --git a/setup/action.yml b/setup/action.yml
--- a/setup/action.yml
+++ b/setup/action.yml
@@ -145,8 +145,7 @@ runs:
         npm i
         npm run prep
 
-    - if: ${{ env.HAS_NEXTJS_EXAMPLES == 'true' || env.HAS_NEXTJS_EXAMPLES == true }}
-      name: Setup auth-react nextjs application
+    - name: Setup auth-react nextjs application
       working-directory: ${{ inputs.path }}/examples/for-tests-nextjs/
       env:
         # Step-specific
@@ -156,8 +155,15 @@ runs:
         REACT_APP_API_PORT: ${{ env.AUTH_REACT__APP_SERVER }}
       shell: bash
       run: |
-        npm i
-        npm run prep
+        if [ "$TESTING_PLATFORM" == "nextjs" ]; then
+          if [ "$HAS_NEXTJS_EXAMPLES" == "true" ]; then
+            npm i
+            npm run prep
+          else
+            echo "nextjs test found but examples not found."
+            exit 1
+          fi
+        fi
 
     - if: ${{ inputs.persist-workspace == 'true' || inputs.persist-workspace == true }}
       uses: bissolli/gh-action-persist-workspace@v2
